### ISSUE TITLE
Use nuxt-property-decorator

### ISSUE THREAD

**Issue by envision** [Al-un/nuxt-ts#1]
Have you noticed there is nuxt-property-decorator instead of vue-property-decorator...you might want to use it instead. Thanks!

https://github.com/nuxt-community/nuxt-property-decorator

**Comment by Al-un** [comment]
Ow... thanks 👍  I will check it out

**Comment by Kosmonaft** [comment]
I believe that thanks to nuxt-property-decorator the Store section can be simplified

**Comment by Al-un** [comment]
@Kosmonaft Sorry if I misunderstood but do you mean that it can be more simplified than the current version?

**Comment by Kosmonaft** [comment]
@Al-un  . Yeah I reckon it can be simplified compare to the current version. Unfortunately I made a mistake as the package which I was thinking about is [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators)
It has as well very handy @MutationAction method.

**Comment by Al-un** [comment]
@Kosmonaft Thanks for pointing this out. `vuex-module-decorators` indeeds looks cool but I did not have an opportunity to try it yet. I plan to do it but not in this project. The reason I want to stick close to the _old and boring Vue way_ is, as I did for a side project, to handle a migration from plain Vue to Nuxt.js. By using the Vue way, Vuex code can _almost_ be copy pasted.
